package com.suinsit.webapp.config;

public enum ENVIROMENTS {
	SUINSIT_HOME,
	SUINSIT_SOURCE,
	SUINSIT_TMP,
	SUINSIT_BACKUPS,
	SUINSIT_VERSIONS,
	SUINSIT_CUSTOMER,
	SUINSIT_LICENCE,
	SUINSIT_MODE,
	SUINSIT_ENVIROMENT,
	SUINSIT_EXECUTION,
	SUINSIT_LOGS,
	JAVA_OPTIONS,
	SUINSIT_BBDD,
	SUINSIT_BBDD_URL,   
	SUINSIT_BBDD_USERNAME,     
	SUINSIT_BBDD_PASSWORD,
	SUINSIT_BBDD_DRIVER
}
